spring.application.name=SpeechToText-Assignment1

server.port=8080

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=10s

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

spring.threads.virtual.enabled=true
spring.main.keep-alive=true